# Generated by Django 3.2.5 on 2021-11-17 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlepost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 15, 57, 31, 622655, tzinfo=utc)),
        ),
    ]
